version: '3.4'
services:
  mysql:
    # MySQL Database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: rinha
    ports:
      - 4444:3306
    expose:
      - 4444
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p12345678"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  app1: &app
    build: .
    hostname: app1
    environment:
      PORT: 3000
      DB_HOSTNAME: "mysql"
      DB_USERNAME: "root"
      DB_PASSWORD: "12345678"
      DB_DATABASE: "rinha"
      DB_PORT: 3306
      NODE_ENV: production
    expose:
      - "3000"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  app2:
    <<: *app
    hostname: app2

  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
